"""Change explicit datatype to string

Revision ID: 093c8684bba4
Revises: 8c989b2e1de8
Create Date: 2024-05-12 15:45:01.523477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093c8684bba4'
down_revision = '8c989b2e1de8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
