"""Added autoincermenet ID

Revision ID: 0ac1d8064733
Revises: 938e0e116f16
Create Date: 2024-05-12 14:41:50.034677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac1d8064733'
down_revision = '938e0e116f16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
