"""Default fate as today

Revision ID: 8c989b2e1de8
Revises: 0ac1d8064733
Create Date: 2024-05-12 14:42:52.705732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c989b2e1de8'
down_revision = '0ac1d8064733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
