"""Initial migration

Revision ID: 938e0e116f16
Revises: 
Create Date: 2024-05-11 16:42:07.498996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938e0e116f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('added_on', sa.Date(), nullable=True),
    sa.Column('deleted_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)
    op.create_index(op.f('ix_podcasts_title'), 'podcasts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcasts_title'), table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_table('podcasts')
    # ### end Alembic commands ###
