"""Added Episodes Model 2

Revision ID: f605cb12333f
Revises: 093c8684bba4
Create Date: 2024-05-12 15:58:48.281940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f605cb12333f'
down_revision = '093c8684bba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('episode_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('added_on', sa.Date(), nullable=True),
    sa.Column('deleted_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_index(op.f('ix_episodes_title'), 'episodes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_title'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
