"""Added RSS Field

Revision ID: ffe1e1bccbff
Revises: f605cb12333f
Create Date: 2024-05-12 21:39:36.821491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe1e1bccbff'
down_revision = 'f605cb12333f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('rss', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'rss')
    # ### end Alembic commands ###
